version: '3.3'

services:
  # MySQL service
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjs_db
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  # NestJS service
  nestjs:
    build:
      context: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - mysql
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # Giao diện web + API
      - "9001:9001"   # Console admin (optional)
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    restart: always

  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/my-bucket;
      exit 0;
      "

volumes:
  mysql-data:
    driver: local
  minio-data:
    driver: local
