version: '3.3'

services:
  # MySQL service
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjs_db
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  # NestJS service
  nestjs:
    build:
      context: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
